# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import main_pb2 as main__pb2


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProfile = channel.unary_unary(
                '/users.UserService/CreateProfile',
                request_serializer=main__pb2.CreateProfileRequest.SerializeToString,
                response_deserializer=main__pb2.CreateProfileResponse.FromString,
                )
        self.Authenticate = channel.unary_unary(
                '/users.UserService/Authenticate',
                request_serializer=main__pb2.AuthenticateRequest.SerializeToString,
                response_deserializer=main__pb2.AuthenticateResponse.FromString,
                )
        self.CreateOffer = channel.unary_unary(
                '/users.UserService/CreateOffer',
                request_serializer=main__pb2.CreateOfferRequest.SerializeToString,
                response_deserializer=main__pb2.CreateOfferResponse.FromString,
                )
        self.GetOffers = channel.unary_unary(
                '/users.UserService/GetOffers',
                request_serializer=main__pb2.GetOffersRequest.SerializeToString,
                response_deserializer=main__pb2.GetOffersResponse.FromString,
                )
        self.CreateIncident = channel.unary_unary(
                '/users.UserService/CreateIncident',
                request_serializer=main__pb2.CreateIncidentRequest.SerializeToString,
                response_deserializer=main__pb2.CreateIncidentResponse.FromString,
                )
        self.GetIncidents = channel.unary_unary(
                '/users.UserService/GetIncidents',
                request_serializer=main__pb2.GetIncidentsRequest.SerializeToString,
                response_deserializer=main__pb2.GetIncidentsResponse.FromString,
                )


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Authenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOffers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIncident(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIncidents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProfile,
                    request_deserializer=main__pb2.CreateProfileRequest.FromString,
                    response_serializer=main__pb2.CreateProfileResponse.SerializeToString,
            ),
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=main__pb2.AuthenticateRequest.FromString,
                    response_serializer=main__pb2.AuthenticateResponse.SerializeToString,
            ),
            'CreateOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOffer,
                    request_deserializer=main__pb2.CreateOfferRequest.FromString,
                    response_serializer=main__pb2.CreateOfferResponse.SerializeToString,
            ),
            'GetOffers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOffers,
                    request_deserializer=main__pb2.GetOffersRequest.FromString,
                    response_serializer=main__pb2.GetOffersResponse.SerializeToString,
            ),
            'CreateIncident': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIncident,
                    request_deserializer=main__pb2.CreateIncidentRequest.FromString,
                    response_serializer=main__pb2.CreateIncidentResponse.SerializeToString,
            ),
            'GetIncidents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIncidents,
                    request_deserializer=main__pb2.GetIncidentsRequest.FromString,
                    response_serializer=main__pb2.GetIncidentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'users.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.UserService/CreateProfile',
            main__pb2.CreateProfileRequest.SerializeToString,
            main__pb2.CreateProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.UserService/Authenticate',
            main__pb2.AuthenticateRequest.SerializeToString,
            main__pb2.AuthenticateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.UserService/CreateOffer',
            main__pb2.CreateOfferRequest.SerializeToString,
            main__pb2.CreateOfferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOffers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.UserService/GetOffers',
            main__pb2.GetOffersRequest.SerializeToString,
            main__pb2.GetOffersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateIncident(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.UserService/CreateIncident',
            main__pb2.CreateIncidentRequest.SerializeToString,
            main__pb2.CreateIncidentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIncidents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.UserService/GetIncidents',
            main__pb2.GetIncidentsRequest.SerializeToString,
            main__pb2.GetIncidentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
